### PR TITLE
CA-155178: Remove squeeze_xen cache if domain disappear

### PR DESCRIPTION
**Pull request by cheng--zhang**
Cleanup disappear domains in domain make to avoid dirty domain cache

Signed-off-by: Cheng Zhang <cheng.zhang@citrix.com>

### CODE REVIEW

**Comment by johnelse** [comment]
@cheng--zhang has pointed out that the trunk code seems to be missing [this commit](https://github.com/xapi-project/xen-api/commit/5e129f446abd0f56273dc74ea884d3a352eb6c46).

@djs55 - do you think it's safe to merge this now, or should we try and get trunk up to date first?

**Comment by djs55** [comment]
Ouch. I would be much happier if we got trunk up to date first, and then
merge this.

On Thu, Feb 12, 2015 at 11:13 PM, John Else <notifications@github.com>
wrote:

> @cheng--zhang <https://github.com/cheng--zhang> has pointed out that the
> trunk code seems to be missing this commit
> <https://github.com/xapi-project/xen-api/commit/5e129f446abd0f56273dc74ea884d3a352eb6c46>
> .
>
> @djs55 <https://github.com/djs55> - do you think it's safe to merge this
> now, or should we try and get trunk up to date first?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xapi-project/squeezed/pull/32#issuecomment-74174196>.
>



-- 
Dave Scott

**Comment by johnelse** [comment]
Trunk and creedence have diverged quite a bit. [This commit](https://github.com/xapi-project/xen-api/commit/5e129f446abd0f56273dc74ea884d3a352eb6c46) is missing from trunk, but trunk instead has [this commit](https://github.com/xapi-project/squeezed/commit/32e6b135f2618e18ea50e91fbeac2416cefb7124). I propose we sort this out after Cream is released (unless you want to have a go @djs55?).

**Comment by jonludlam** [comment]
Well Cream has gone out the door. Time to get back to this one?

**Comment by euanh** [comment]
@cheng--zhang: Could you please check that this change is still correct for the current state of trunk?

**Comment by cheng--zhang** [comment]
Hi @euanh 
Thanks a lot for your comment.
I think currenly we still miss the commit which point of by John, here: https://github.com/xapi-project/xen-api/commit/5e129f446abd0f56273dc74ea884d3a352eb6c46

If we decide to merge my commit first, I think the current code is OK.
Do you think so?

**Comment by simonjbeaumont** [comment]
@euanh looks like the latest action is with you... :point_left:

**Comment by johnelse** [comment]
I'm going to close this for now, since the rest of trunk squeezed needs to be brought up to date with the changes in 6.5 first (see https://issues.citrite.net/browse/CP-13136). Once that is done, this can be reopened (or reworked if necessary).

**Pull request closed without merging**
